# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'


development:
  adapter: postgresql
  database: my_profile_development
  pool: 5
  timeout: 5000
  host: localhost
  username: profileapp
  password: teamror
test:
  adapter: postgresql
  database: my_profile_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_profile_production
  pool: 5
  timeout: 5000